name: CI/CD (Part 3)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      uses: docker/compose-action@v2
      with:
        docker-compose-version: 'latest'

    - name: Make test.sh executable
      run: chmod +x ./test.sh

    - name: Run tests
      run: ./test.sh
